-- 当前日期
SELECT CURRENT_DATE();
SELECT CURDATE();

-- 当前时间
SELECT CURRENT_TIME();
SELECT CURTIME();

-- 获取时间间隔
SELECT TIMESTAMPDIFF(HOUR,'2023-1-1','2023-1-3');
SELECT TIMESTAMPDIFF(DAY,'2023-1-1','2023-1-3');

SELECT TIMESTAMPDIFF(YEAR,birthday,CURDATE()) 年龄, `name` 
FROM employee
ORDER BY 年龄;